# docker-compose.yml

version: '3.8'

services:
  app:
    build: .
    environment:
      - BOT_EMAIL=${BOT_EMAIL}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - IMAP_SERVER=${IMAP_SERVER}
      - IMAP_PORT=${IMAP_PORT}
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - DB_TYPE=${DB_TYPE}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - URL=${URL}
      - CHECK_INTERVAL=${CHECK_INTERVAL}
      - EMAIL_CHECK_INTERVAL=${EMAIL_CHECK_INTERVAL}
      # Uncomment if using Telegram and Discord
      # - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      # - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      # - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
    networks:
      - app_network
    depends_on:
      - db
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  db_data:

networks:
  app_network:
    driver: bridge
